### ISSUE TITLE
Coop images are blocked by CORB

### ISSUE THREAD

**Issue by retr0mouse** [rakenduste-programmeerimine-2022/soodne#89]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/22565000/205521671-aa63b0fc-8cd6-4c6c-96fc-9374c00b6913.png">

**Comment by AskMikk** [comment]
Checked - a problem in the coop site, when  they adding new products - the names of the pictures are regenerated (need to know when they have the loading of the products)
